### ISSUE TITLE
Will only work if my xbox was recently on

### ISSUE THREAD

**Issue by J123J123** [Schamper/xbox-remote-power#13]
The code is working for me both remotely and locally, however it will not work if my xbox has been powered off for more then 5 minutes. If I recently had the xbox on, it will work. Any thoughts?

**Comment by derfreimann** [comment]
It _does_ work, you only need like a million tries scattered over a pretty vast period of time... I usually give it a couple of tries every 5-10 minutes and eventually it will turn on. 
However, like you said, it instantly turns on instantly if the xbox was powered off just a couple of minutes ago.
Must be that an update kind of messed the standby mode and puts the xbox in a deeper sleep than it should :/

**Comment by Schamper** [comment]
All I know is that it's probably not something wrong with this script, since I have this issue with the official Smartglass apps as well. Seems to have started with the NXOE update...

**Comment by marmarjohnson** [comment]
Yeah, the problem exists in the XBox program on Windows 10 and the Smartglass, too.  Originally, I too thought the issue is that the XBox update put the machine in too deep a sleep, but it can't be that---at least in general.  One work-around to get the xbox to remote power-on is is to purchase an app via the smartglass app.  The Xbox will wake-up to download it (have confirmed myself).  So at least for app purchases, the XBox is still listening.  I wonder if it's possible to use the xbox app purchase path to kick it on?  My hope for now is that wit the next Xbox update, the issue is fixed.

**Comment by J123J123** [comment]
marmarjohnson that sounds like an interesting idea. Your quick fix will not work for me since the xbox I want to remotely turn on is not my "home xbox" therefore I cannot start a download from my Smartglass app. But I too wonder if you would be able to use the"xbox app purchase path to kick it on".  In theory that sounds like a promising idea, but i don't have the skills/knowledge to look into it.

**Comment by Schamper** [comment]
Latest commit will keep sending the power on packets until one sticks, so you can try that.

**Comment by Tronix117** [comment]
Unfortunately, it doesn't seem to work anymore for me (even last commit) :/

**Comment by Schamper** [comment]
Lets continue this issue in #5, since this is actually a duplicate of that one.
