### ISSUE TITLE
Byte string to turn off xbox? 

### ISSUE THREAD

**Issue by ankitbhatia** [Schamper/xbox-remote-power#3]
Hi,

This works great for turning on my xbox programatically. I want to be able to turn it off as well. Any ideas about how I should proceed figuring out the byte string?

I tried recording the communication from the xbox windows app when I give the command but I can't seem to figure out the correct encoding. 

Any ideas would be great!

Thanks!

**Comment by Schamper** [comment]
Can I ask what dashboard you're running on the Xbox One? Are you running the preview for the NXOE or the regular stable? Reason why I'm asking is because it looks like this method of turning on your Xbox was fixed in the NXOE, at least for me and a couple others.

As for turning it off, let me try and explain a bit how the communication between the Xbox app and the One works:

When you turn on your Xbox from within the app, the following happens:
- The app will broadcast "magic wake up" packets over the network
- The app will broadcast and send discovery packets to the Xbox One
- When the Xbox "wakes up", it'll start responding to these discovery packets
- Anything from here onwards is encrypted

So this is probably the reason why you can't figure out the encoding. Once the Xbox is actually on, all communication will be encrypted, so (most likely) also the power off command. Some work on figuring out how this works is being done, though.

I think you can still turn it off from within the Xbox app. Otherwise you can stream it and hold the Xbox button on your controller and turn it off that way.

**Comment by ankitbhatia** [comment]
I'm running the regular stable. And I noticed last night that just sending
the ping packet wakes up the xbox (I think).

**Comment by ankitbhatia** [comment]
By the way, any chance you could send me an invite for the preview for xbox one? I have been wanting to try it out for a while. Thanks!

**Comment by Schamper** [comment]
Sure, what is your gamertag?

**Comment by ankitbhatia** [comment]
Blooper1989 Thanks!

**Comment by Schamper** [comment]
I sent you an invite but it might be a while until you receive a message about it, if at all.

**Comment by ankitbhatia** [comment]
Thanks a lot. Yeah I heard their preview program is running at full
capacity!

**Comment by Schamper** [comment]
https://github.com/OpenXbox/xbox-smartglass-core-python
