### ISSUE TITLE
‘AttributeError’ thrown on OS X

### ISSUE THREAD

**Issue by beornlake** [Schamper/xbox-remote-power#8]
Running the command via the `bash` script on OS X (10.11.2) can generate the following output. The script still causes the Xbox to power-up, even with this error.

```
$ ./xbox-remote-power.sh 
Sending power on packets to 172.16.28.7
Xbox should turn on now
Traceback (most recent call last):
  File "xbox-remote-power.py", line 98, in <module>
    main()
  File "xbox-remote-power.py", line 68, in main
    s.send(bytes.fromhex(XBOX_PING))
AttributeError: type object 'str' has no attribute 'fromhex'
```

Current Python library:

```
$ which python
/usr/bin/python

$ python --version
Python 2.7.10
```

**Comment by TimoVerbrugghe** [comment]
Seems I seem to be having the same problem. Ubuntu 15.10, python version 2.7.10

**Comment by JDQuackers** [comment]
This is caused by line 68 added by @derfreimann in the last pull request:
`bytes.fromhex()` is a Python 3.x class method, and should either be wrapped in `if py3` blocks like the other instances of `bytes.fromhex` or all of those should be converted to the Py2/3 friendly `bytearray.fromhex`

Actually, I think I'll do a quick pull request for converting all of those blocks to the latter since it will clean things up a bit anyway

**Comment by Schamper** [comment]
@JDQuackers :+1: looking forward to your PR.
